name: Docker Image (Linux)

on:
  workflow_dispatch:

permissions:
  actions: write
  contents: read
  packages: write

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      DOCKERFILE: |
        FROM mcr.microsoft.com/dotnet/runtime:8.0
        ARG TARGETARCH
        COPY MinecraftClient-${TARGETARCH} /opt/MinecraftClient
        RUN apt-get update && \ 
            apt-get install -y unzip && \
            rm -rf /var/lib/apt/lists/* && \
            mkdir /opt/data
        ENTRYPOINT ["/opt/MinecraftClient"]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

#    - name: Login to Docker Hub
#      uses: docker/login-action@v3
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Buildkit
      uses: docker/setup-buildx-action@v3

    - name: Download
      run: |
        RELEASE_TAG=${MCC_VERSION:-$(curl -s -v https://github.com/MCCTeam/Minecraft-Console-Client/releases/latest 2>&1 | grep -i location: | tr -d '\r' | cut -d/ -f8)} && \
        for ARCH in x64 arm64 arm; do
          curl https://github.com/MCCTeam/Minecraft-Console-Client/releases/download/${RELEASE_TAG}/MinecraftClient-${RELEASE_TAG}-${MCC_PLATFORM:=linux}-${ARCH/x64/amd4} --output MinecraftClient-${ARCH/x64/amd4}
        done
        chmod +x MinecraftClient*

    - name: Build
      run: echo "$DOCKERFILE" | docker buildx build --platform=linux/amd64,linux/arm64,linux/arm/v7 -t ghcr.io/amitie10g/minecraft-console-client -f - --push .
